import Config

# Configure your database
# Credenciais alinhadas ao docker-compose.yml (serviço postgres) na raiz do
# repositório — ver docs/architecture.md. Se estiver usando uma instância
# nativa do PostgreSQL em vez do Docker, crie o role/banco correspondentes.
config :tora_dos_burro, ToraDosBurro.Repo,
  username: "tora",
  password: "tora_dev_password",
  hostname: "localhost",
  database: "tora_dos_burro_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :tora_dos_burro, ToraDosBurroWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "2rP5oSBDtapVmbGejT7ehfN8Eml1kP4ivdLHlpJ6w9/wvvPfU0tETDaLL3+tV32k",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :tora_dos_burro, dev_routes: true

# Guardian (JWT) — chave só de desenvolvimento, nunca usada em produção
# (runtime.exs le de GUARDIAN_SECRET_KEY para prod). Gerada com
# `mix guardian.gen.secret`.
config :tora_dos_burro, ToraDosBurro.Guardian,
  secret_key: "pufN052OsVcTVbvaXElKSZXkV0LwMAbUkhL1SWrql8DTMRDuQHGNo_51syCNrIpN"

# LiveKit (FASE 9, Go Live) — credenciais padrão do modo `--dev` do próprio
# livekit-server (ver docker-compose.yml), nunca usadas em produção
# (runtime.exs lê de LIVEKIT_API_KEY/LIVEKIT_API_SECRET/LIVEKIT_URL para prod).
config :tora_dos_burro, ToraDosBurro.GoLive.LiveKitToken,
  api_key: "devkey",
  api_secret: "secret",
  url: "ws://localhost:7880"

# CORS (FASE 11) — origem do cliente Electron em dev: o dev server do Vite
# (electron-vite), porta padrão do Vite.
config :cors_plug, origin: ["http://localhost:5173"]

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
