defmodule ToraDosBurroWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :tora_dos_burro

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_tora_dos_burro_key",
    signing_salt: "JfWB/QDB",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # `check_origin: false`: essa checagem protege contra um site malicioso
  # abrindo WebSocket usando a *sessão de navegador* de alguém (cookie) —
  # não se aplica aqui, o cliente nunca é um navegador (é o app Electron) e
  # a autenticação é só o token Guardian no query param, nunca cookie (ver
  # UserSocket.connect/3). Sem isso, todo handshake vindo do app empacotado
  # falhava com 403 — Origin de um `file://` nunca bate com nenhum host
  # configurado. Só em dev não aparecia porque o Endpoint inteiro já roda
  # com check_origin: false lá (boilerplate padrão do `mix phx.new`, sem
  # relação com o motivo real daqui) — nunca foi testado de verdade contra
  # produção antes.
  socket "/socket", ToraDosBurroWeb.UserSocket, websocket: [check_origin: false]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :tora_dos_burro,
    gzip: not code_reloading?,
    only: ToraDosBurroWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :tora_dos_burro
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # Cliente Electron roda em origem diferente (dev server do Vite em dev,
  # file://custom protocol em produção) — sem isso o navegador bloqueia todo
  # fetch pro backend. Origem configurada via `config :cors_plug, origin:`
  # (dev.exs / runtime.exs), lida em runtime pelo próprio CORSPlug.
  plug CORSPlug

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug ToraDosBurroWeb.Router
end
